# Generated by Django 4.2.4 on 2024-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workos_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
