# Generated by Django 4.2.4 on 2024-01-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_deleted_at_department_deleted_at"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercompanies",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="userdepartments",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="company.department",
            ),
        ),
    ]
