# Generated by Django 4.2.4 on 2024-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_workos_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="workos_id",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
