# Generated by Django 4.2.4 on 2024-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_customuser_workos_id_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercompanies",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
