# Generated by Django 4.2.4 on 2024-02-08 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_usercompanies_company_and_more"),
        ("user", "0004_alter_usercompanies_id"),
    ]

    operations = []
