# Generated by Django 4.2.4 on 2024-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_merge_20240208_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
