#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
#npm test

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '💩🙈🙉💩 Pee Pee Poo Poo. Styling is not ok. 💩🙈🙉💩
    Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 No no no no! 😤🏀👋😤
        ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🫠😂❌🫠 Failed Type check. 🫠😂❌🫠
              Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... styling and code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call chatGPT... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Man this shit is strict. Oh well, you win this time... I am committing this now. ✅✅✅✅'
