# Generated by Django 4.2.2 on 2023-06-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('interview', '0002_interviewroundquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewround',
            name='interviewer',
        ),
        migrations.CreateModel(
            name='InterviewerRoundInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewround')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='user.user')),
            ],
        ),
    ]
