# Generated by Django 4.2.2 on 2023-07-04 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0002_interviewroundquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interviewround",
            name="interviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
