# Generated by Django 4.2.3 on 2023-07-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0003_alter_customuser_company"),
        ("interview", "0003_alter_interviewround_candidate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewround",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="interviewround",
            name="interviewer",
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topics_text", models.CharField(max_length=200)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewRoundTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interviewround",
                    ),
                ),
                ("topic", models.ManyToManyField(to="interview.topic")),
            ],
        ),
        migrations.CreateModel(
            name="InterviewRoundInterviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interviewround",
                    ),
                ),
                ("interviewer", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="interviewroundquestion",
            name="interview_round_topics",
            field=models.ManyToManyField(to="interview.interviewroundtopic"),
        ),
    ]
