version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend_django:
    build: ./backend_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_django:/backend_django
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}


