# https://github.com/standardrb/standard
# .rubocop.yml
AllCops:
  NewCops: enable

# Makes prettier and Rubocop not yell at each other.
inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
