# Generated by Django 4.2.4 on 2024-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0004_comment_deleted_at_comment_deleted_by_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
