# Generated by Django 4.2.4 on 2024-01-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("question", "0004_comment_deleted_at_comment_deleted_by_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="company",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
    ]
