# Generated by Django 4.2.4 on 2024-01-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_department_deleted_at"),
        ("question", "0005_question_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="company",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
    ]
