# Generated by Django 4.2.4 on 2024-01-03 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0005_questionbank_description"),
        ("question", "0006_comment_company"),
    ]

    operations = []
