# Generated by Django 4.2.4 on 2024-01-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0007_merge_20240103_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="competency",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
