# Generated by Django 4.2.3 on 2023-10-10 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="company_id",
            new_name="company",
        ),
    ]
