# Generated by Django 4.2.7 on 2023-11-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transcription", "0001_initial"),
        ("question_response", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="transcript_chunks",
            field=models.ManyToManyField(related_name="answer", to="transcription.transcriptchunk"),
        ),
    ]
