# Generated by Django 4.2.7 on 2023-11-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0002_template_image"),
        ("question_response", "0004_remove_interviewerfeedback_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewerfeedback",
            name="template_question",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview_templates.templatequestion",
                null=True,  # Add this line to allow null values temporarily
            ),
        ),
    ]
