# Generated by Django 4.2.4 on 2024-03-04 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_response", "0011_answer_created_at_answer_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="embedding",
        ),
    ]
