# Generated by Django 4.2.6 on 2023-10-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_department"),
        ("interview_templates", "0002_alter_template_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.department",
            ),
        ),
    ]
