# Generated by Django 4.2.6 on 2023-10-06 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("user", "0003_remove_customuser_company_user_companies_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User_Companies",
            new_name="UserCompanies",
        ),
    ]
