# Generated by Django 4.2.3 on 2023-10-10 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_role_remove_customuser_role_userdepartments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdepartments",
            old_name="department_id",
            new_name="department",
        ),
    ]
