# Generated by Django 4.2.5 on 2023-10-20 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_rename_company_id_department_company"),
        ("user", "0006_rename_department_id_userdepartments_department"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userdepartments",
            unique_together={("user", "department")},
        ),
    ]
