# Generated by Django 4.2.7 on 2023-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="template_images/"),
        ),
    ]
