# Generated by Django 4.2.7 on 2023-12-03 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview_templates", "0002_template_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="interviewers",
            field=models.ManyToManyField(related_name="template_interviewers", to=settings.AUTH_USER_MODEL),
        ),
    ]
