# Generated by Django 4.2.4 on 2023-12-30 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
        ("interview_templates", "0004_template_deleted_at_template_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatequestion",
            name="company",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AddField(
            model_name="templatequestion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_question_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatetopic",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_topic_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
