# Generated by Django 4.2.4 on 2024-01-02 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0005_templatequestion_company_templatequestion_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatetopic",
            old_name="company_id",
            new_name="company",
        ),
    ]
