# Generated by Django 4.2.4 on 2024-03-03 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0007_remove_templatequestion_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="location",
        ),
    ]
