# Generated by Django 4.2.2 on 2023-06-30 01:49

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('question_response', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
