# Generated by Django 4.2.4 on 2023-08-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summary",
            old_name="text",
            new_name="description",
        ),
        migrations.AddField(
            model_name="summary",
            name="qa_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
