# Generated by Django 4.2.7 on 2023-11-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_response", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewerfeedback",
            name="note",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="interviewerfeedback",
            name="reaction",
            field=models.IntegerField(
                choices=[
                    (1, "Fire"),
                    (2, "Thumbs Up"),
                    (3, "Thumbs Down"),
                    (4, "Heart"),
                    (5, "Laugh"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewerfeedback",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ],
                null=True,
            ),
        ),
    ]
