# Generated by Django 4.2.7 on 2023-11-24 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("question_response", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewerfeedback",
            name="score",
        ),
        migrations.AddField(
            model_name="interviewerfeedback",
            name="comment",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="interviewerfeedback",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="interviewerfeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
