# Generated by Django 4.2.7 on 2023-11-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0002_template_image"),
        ("question_response", "0006_alter_interviewerfeedback_template_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewerfeedback",
            name="template_question",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview_templates.templatequestion",
            ),
        ),
    ]
