# Generated by Django 4.2.7 on 2023-11-30 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_response", "0004_interviewerfeedback_time"),
        ("question_response", "0007_alter_interviewerfeedback_template_question"),
    ]

    operations = []
