# Generated by Django 4.2.2 on 2023-06-30 01:51

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0003_remove_question_interview_round"),
    ]

    operations = [
        VectorExtension(),
    ]
