# Generated by Django 4.2.3 on 2023-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0003_remove_question_interview_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("questions", models.ManyToManyField(to="question.question")),
            ],
        ),
    ]
