# Generated by Django 4.2.2 on 2023-06-30 03:11

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_remove_question_competency_competency_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_embeddings',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
