# Generated by Django 4.2.3 on 2023-07-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_questionbank'),
        ('question', '0006_question_question_text_embeddings'),
    ]

    operations = [
    ]
