# Generated by Django 4.2.5 on 2023-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
