# Generated by Django 4.2.7 on 2023-11-07 14:18

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interview", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("embedding", pgvector.django.VectorField(dimensions=1536, null=True)),
                ("start_time", models.IntegerField()),
                ("end_time", models.IntegerField()),
                ("speaker_object_id", models.PositiveIntegerField(null=True)),
                (
                    "interview_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_chunks",
                        to="interview.interviewround",
                    ),
                ),
                (
                    "speaker_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
