# Generated by Django 4.2.4 on 2024-02-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_transcriptchunk_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptchunk",
            name="speaker_object_id",
            field=models.CharField(null=True),
        ),
    ]
