# Generated by Django 4.2.7 on 2023-11-02 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview_templates", "0001_initial"),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewroundquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_round_questions",
                to="interview_templates.templatequestion",
            ),
        ),
        migrations.AddField(
            model_name="interviewround",
            name="candidate",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interviewround",
            name="interviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
