# Generated by Django 4.2.6 on 2023-10-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="candidate",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interviewround",
            name="interviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
