# Generated by Django 4.2.7 on 2023-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewround",
            name="meeting_room_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
