# Generated by Django 4.2.7 on 2023-11-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0003_interviewround_meeting_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview.candidate",
            ),
        ),
    ]
