# Generated by Django 4.2.7 on 2023-11-28 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0005_interviewroundquestion_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewroundquestion",
            name="time",
        ),
    ]
