# Generated by Django 4.2.7 on 2023-11-07 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interview", "0001_initial"),
        ("interview_templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewroundquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_round_questions",
                to="interview_templates.templatequestion",
            ),
        ),
        migrations.AddField(
            model_name="interviewround",
            name="candidate",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="interview.candidate"),
        ),
        migrations.AddField(
            model_name="interviewround",
            name="interviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
