# Generated by Django 4.2.4 on 2024-01-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_department_deleted_at"),
        ("interview", "0009_candidate_deleted_at_candidate_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="company",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AddField(
            model_name="interviewroundquestion",
            name="company",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
    ]
