# Generated by Django 4.2.4 on 2024-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_rename_company_id_interviewround_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewround",
            name="thumbnail",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
