# Generated by Django 4.2.4 on 2024-01-02 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0010_candidate_company_interviewroundquestion_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewround",
            old_name="company_id",
            new_name="company",
        ),
    ]
