# Generated by Django 4.2.4 on 2024-02-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview_templates", "0007_remove_templatequestion_company_and_more"),
        ("interview", "0011_interviewround_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="template_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview_templates.template",
            ),
        ),
    ]
