# Generated by Django 4.2.4 on 2024-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0012_alter_interviewround_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="thumbnail",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="interview-thumbnails/"),
        ),
    ]
