# Generated by Django 4.2.4 on 2024-02-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0013_alter_interviewround_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewround",
            name="template_id",
            field=models.IntegerField(default=55),
        ),
    ]
