# Generated by Django 4.2.4 on 2024-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0014_alter_interviewround_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewround",
            name="icon",
            field=models.TextField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
