# Generated by Django 4.2.4 on 2024-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0015_interviewround_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="interviewround",
            name="decision_hire",
            field=models.IntegerField(
                blank=True, choices=[(1, "Hire"), (2, "Dont Hire"), (3, "Strong Hire")], default=None, null=True
            ),
        ),
    ]
