# Generated by Django 4.2.4 on 2024-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0016_candidate_email_interviewround_decision_hire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewroundquestion",
            name="rating",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
