# Generated by Django 4.2.4 on 2024-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_deleted_at_department_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="workos_orgID",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
