# Generated by Django 4.2.4 on 2024-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_company_workos_orgid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="workos_orgID",
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
