name: Frontend

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ./frontend/.nvmrc
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Formatting
        working-directory: ./frontend
        run: npm run check-format

      - name: Lint
        working-directory: ./frontend
        run: npm run check-lint

      - name: Type check
        working-directory: ./frontend
        run: npm run check-types

      - name: Build
        working-directory: ./frontend
        run: npm run build
